version: "3.7"

services:
  postgres:
    build:
      context: psql
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    networks:
      - main_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -d admin_panel -c 'SELECT 2;'" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: admin_panel
    container_name: fast_api_server
    restart: always
    networks:
      - main_network
    environment:
      admin_panel_psql__host: postgres
      admin_panel_server__host: fast_api_server
    depends_on:
      - postgres

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: proxy_server
    ports:
      - "8000:8000"
    restart: always
    networks:
      - main_network
    depends_on:
      - app


networks:
  main_network:
